app:
  download_dir: "./downloads/"
  file_path: "https://discogs-data.s3-us-west-2.amazonaws.com/data/{year}/"
  file_name: "discogs_{date}_{type}.{extension}"
  mapping_file: "config/mapping.{type}.yml"

elasticsearch:
  host: "localhost"
  scheme: "http"
  port: 9200
  indexes:
    settings:
      number_of_shards: 1
      number_of_replicas: 0
      index:
        analysis:
          filter: null,
          analyzer:
            edge_ngram_analyzer:
              filter:
                - 'lowercase'
              tokenizer: "edge_ngram_tokenizer"
            edge_ngram_search_analyzer:
              tokenizer: "lowercase"
          tokenizer:
            edge_ngram_tokenizer:
              type: "edge_ngram"
              min_gram: 2
              max_gram: 30
              token_chars:
                - "letter"

discogs:
  prefix_url: "https://discogs-data.s3-us-west-2.amazonaws.com/data/"

types:
  artists:
    id: "string(id)"
    name: "string(name)"
    realname: "string(realname)"
    profile: "string(profile)"
    namevariations: "namevariations/name//text()"
    aliases: "aliases/name//text()"
    url: "string(url)"
    urls: "urls/url//text()"
    # data_quality: "data_quality[0]"
    groups: "groups/name//text()"
    members:
      xpath: "members/name"
      id: "string(@id)"
      name: "string()"
  masters:
    id: "string(@id)"
    main_release: "string(main_release)"
    artists:
      xpath: "artists/artist"
      id: "string(id)"
      name: "string(name)"
      anv: "string(anv)"
      join: "string(join)"
      role: "string(role)"
      tracks: "string(tracks)"
    # data_quality: "data_quality[0].artist"
    genres: "genres/genre//text()"
    notes: "string(notes)"
    styles: "styles/style//text()"
    title: "string(title)"
    year: "string(year)"
    videos:
      xpath: "videos/video"
      # duration: "string(@duration)"
      # embed: "string(@embed)"
      src: "string(@src)"
      title: "string(title)"
      description: "string(description)"
  releases:
    id: "string(@id)"
    status: "string(@status)"
    released: "string(released)"
    master_id: "string(master_id)"
    artists:
      xpath: "artists/artist"
      id: "string(id)"
      name: "string(name)"
      anv: "string(anv)"
      join: "string(join)"
      role: "string(role)"
      tracks: "string(tracks)"
    #extraartists:
    #  xpath: "extraartists/artist"
    #  id: "string(id)"
    #  name: "string(name)"
    #  anv: "string(anv)"
    #  join: "string(join)"
    #  role: "string(role)"
    #  tracks: "string(tracks)"
    #labels:
    #  xpath: "labels/label"
    #  name: "string(@name)"
    #  catno: "string(@catno)"
    #formats:
    #  xpath: "formats/format"
    #  name: "string(@name)"
    #  quantity: "string(@qty)"
    #  text: "string(@text)"
    #  descriptions: "descriptions/description/text()"
    #data_quality: "string(data_quality)"
    tracklist:
      xpath: "tracklist/track"
      position: "string(position)"
      title: "string(title)"
      duration: "string(duration)"
      artists:
        xpath: "artist"
        id: "string(id)"
        name: "string(name)"
        anv: "string(anv)"
        join: "string(join)"
        role: "string(role)"
        tracks: "string(tracks)"
      #extraartists:
      #  xpath: "extraartists"
      #  id: "string(id)"
      #  name: "string(name)"
      #  anv: "string(anv)"
      #  join: "string(join)"
      #  role: "string(role)"
      #  tracks: "string(tracks)"
    #identifiers:
    #  xpath: "identifiers/identifier"
    #  description: "@description"
    #  type: "string(@type)"
    #  value: "string(@value)"
    genres: "genres/genre//text()"
    notes: "string(notes)"
    styles: "styles/style//text()"
    country: "string(country)"
    title: "string(title)"
    #videos:
    #  xpath: "videos/video"
    #  duration: "string(@duration)"
    #  embed: "string(@embed)"
    #  src: "string(@src)"
    #  title: "string(title)"
    #  description: "string(description)"
    #companies:
    #  xpath: "companies/company"
    #  id: "string(id)"
    #  name: "string(name)"
    #  catno: "string(catno)"
    #  entity-type: "string(entity_type)"
    #  entity_type_name: "string(entity_type_name)"
    #  resource_url: "string(ressource_url)"
