properties:
  id:
    type: "integer"
    index: false
  name:
    type: "text"
    analyzer: "edge_ngram_analyzer"
    search_analyzer: "edge_ngram_search_analyzer"
  realname:
    type: "keyword"
    index: false
  profile:
    type: "keyword"
    index: false
    ignore_above: 32000
  url:
    type: "keyword"
    index: false
  urls:
    type: "keyword"
    index: false
  groups:
    type: "keyword"
    index: false
  namevariations:
    type: "keyword"
    index: false
  data_quality:
    type: "keyword"
    index: false
  members:
    properties:
      id:
        type: "integer"
        index: false
      name:
        type: "keyword"
        index: false
  videos:
    properties:
      duration:
        type: "integer"
        index: false
      embed:
        type: "keyword"
        index: false
      src:
        type: "keyword"
        index: false
      title:
        type: "keyword"
        index: false
      description:
        type: "keyword"
        index: false
