properties:
  id:
    type: "integer"
    index: false
  main_release:
    type: "integer"
    index: false
  artists:
    properties:
      id:
        type: "integer"
        index: true
      name:
        type: "keyword"
        index: false
      anv:
        type: "keyword"
        index: false
      join:
        type: "keyword"
        index: false
      role:
        type: "keyword"
        index: false
      tracks:
        type: "keyword"
        index: false
  data_quality:
    type: "keyword"
    index: false
  genres:
    type: "keyword"
    index: false
  notes:
    type: "keyword"
    index: false
    ignore_above: 32000
  styles:
    type: "keyword"
    index: false
  title:
    type: "keyword"
    index: false
  videos:
    properties:
      duration:
        type: "integer"
        index: false
      embed:
        type: "keyword"
        index: false
      src:
        type: "keyword"
        index: false
      title:
        type: "keyword"
        index: false
      description:
        type: "keyword"
        index: false
  year:
    type: "integer"
    index: false
